In [3]:
import pandas as pd
import numpy as np

In [11]:
data={
    "Product" : ["Laptop","Mobile","Tablet","Headphones","TV","Fridge"],
    "Price": [80000, 25000,np.nan,2000,45000,np.nan],
    "Quantity":[5,np.nan,15,8,7,3],
    "Discount":[10,np.nan,5,2,np.nan,8]

}

df=pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
      Product    Price  Quantity  Discount
0      Laptop  80000.0       5.0      10.0
1      Mobile  25000.0       NaN       NaN
2      Tablet      NaN      15.0       5.0
3  Headphones   2000.0       8.0       2.0
4          TV  45000.0       7.0       NaN
5      Fridge      NaN       3.0       8.0

In [12]:
df.dropna(axis=1,how='any')

      Product
0      Laptop
1      Mobile
2      Tablet
3  Headphones
4          TV
5      Fridge

In [ ]:
df.dropna(axis=0,how="any")

      Product    Price  Quantity  Discount
0      Laptop  80000.0       5.0      10.0
3  Headphones   2000.0       8.0       2.0

In [16]:
df.dropna(axis=0,how="all")

      Product    Price  Quantity  Discount
0      Laptop  80000.0       5.0      10.0
1      Mobile  25000.0       NaN       NaN
2      Tablet      NaN      15.0       5.0
3  Headphones   2000.0       8.0       2.0
4          TV  45000.0       7.0       NaN
5      Fridge      NaN       3.0       8.0

In [17]:
df.dropna(axis=1,how="any")

      Product
0      Laptop
1      Mobile
2      Tablet
3  Headphones
4          TV
5      Fridge

In [18]:
df.dropna(axis=1,how="all")

      Product    Price  Quantity  Discount
0      Laptop  80000.0       5.0      10.0
1      Mobile  25000.0       NaN       NaN
2      Tablet      NaN      15.0       5.0
3  Headphones   2000.0       8.0       2.0
4          TV  45000.0       7.0       NaN
5      Fridge      NaN       3.0       8.0

In [31]:
data={
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Heidi"],
    "Age": [25, np.nan, 35, 40, np.nan, 50, np.nan, 60],
    "City": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", np.nan, "San Diego"],
    "Purchaseamount": [100, np.nan, 150, 300, 250, np.nan, 350, 450],
    "Feedback": [5.0, np.nan, 4.0, 3.5, 4.8, np.nan, 3.8, 4.9]
}
df=pd.DataFrame(data)
print("Original DataFrame:")    
df

Original DataFrame:

      Name   Age          City  Purchaseamount  Feedback
0    Alice  25.0      New York           100.0       5.0
1      Bob   NaN   Los Angeles             NaN       NaN
2  Charlie  35.0       Chicago           150.0       4.0
3    David  40.0       Houston           300.0       3.5
4      Eve   NaN       Phoenix           250.0       4.8
5    Frank  50.0  Philadelphia             NaN       NaN
6    Grace   NaN           NaN           350.0       3.8
7    Heidi  60.0     San Diego           450.0       4.9

In [26]:
df.fillna({"Age":20},inplace=True)
df

      Name   Age          City  Purchaseamount  Feedback
0    Alice  25.0      New York           100.0       5.0
1      Bob  20.0   Los Angeles             NaN       NaN
2  Charlie  35.0       Chicago           150.0       4.0
3    David  40.0       Houston           300.0       3.5
4      Eve  20.0       Phoenix           250.0       4.8
5    Frank  50.0  Philadelphia             NaN       NaN
6    Grace  20.0           NaN           350.0       3.8
7    Heidi  60.0     San Diego           450.0       4.9

In [28]:
data={
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Heidi"],
    "Age": [25, np.nan, 35, 40, np.nan, 50, np.nan, 60],
    "City": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", np.nan, "San Diego"],
    "Purchaseamount": [100, np.nan, 150, 300, 250, np.nan, 350, 450],
    "Feedback": [5.0, np.nan, 4.0, 3.5, 4.8, np.nan, 3.8, 4.9]
}
df=pd.DataFrame(data)
print("Original DataFrame:")    
df
df["Age"].fillna(df["Age"].median(),inplace=True)

Original DataFrame:

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_3000\114291939.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(),inplace=True)

In [29]:
df

      Name   Age          City  Purchaseamount  Feedback
0    Alice  25.0      New York           100.0       5.0
1      Bob  40.0   Los Angeles             NaN       NaN
2  Charlie  35.0       Chicago           150.0       4.0
3    David  40.0       Houston           300.0       3.5
4      Eve  40.0       Phoenix           250.0       4.8
5    Frank  50.0  Philadelphia             NaN       NaN
6    Grace  40.0           NaN           350.0       3.8
7    Heidi  60.0     San Diego           450.0       4.9

In [33]:
df["Age"].fillna(method="ffill")

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_3000\310954073.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method="ffill")

0    25.0
1    25.0
2    35.0
3    40.0
4    40.0
5    50.0
6    50.0
7    60.0
Name: Age, dtype: float64

In [34]:
df["Age"].fillna(method="bfill")

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_3000\3345892411.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method="bfill")

0    25.0
1    35.0
2    35.0
3    40.0
4    50.0
5    50.0
6    60.0
7    60.0
Name: Age, dtype: float64

# Whenever there is a categorical column like gender or pass/fail , state/country codes,then we use mode for the null value treatment

## if there are no outliers in the data and it is continuous like sales,profit,units, then we can use mean,median to fill missing values.

#### whenever there is a time series data, data is available in date format then we can use "Forwardfill" ,"Backwardfill", to fill missing values. 
##### Note: sometimes we can split the data and perform both forward fill for weekdays and backward fill for weeekends and try to append data.

In [35]:
### Null value Treatment
 ### check the null values in the dataset
 ### Take the percentage of null values
 ###Confirm the null values
 ### beyond the threshold value we can drop the column
 ### below the threshold value we can keep the column
 ### if it is a numerical column we can fill the null values with mean, median
 ### if it is a categorical column we can fill the null values with mode
 ### if it is a time series data we can fill the null values with forward fill and backward fill

In [36]:
df

      Name   Age          City  Purchaseamount  Feedback
0    Alice  25.0      New York           100.0       5.0
1      Bob   NaN   Los Angeles             NaN       NaN
2  Charlie  35.0       Chicago           150.0       4.0
3    David  40.0       Houston           300.0       3.5
4      Eve   NaN       Phoenix           250.0       4.8
5    Frank  50.0  Philadelphia             NaN       NaN
6    Grace   NaN           NaN           350.0       3.8
7    Heidi  60.0     San Diego           450.0       4.9

In [38]:
df.isna().sum()

Name              0
Age               3
City              1
Purchaseamount    2
Feedback          2
dtype: int64

In [40]:
null_value_table=(df.isna().sum()/df.shape[0])*100

In [44]:
null_value_table[null_value_table>30].index

Index(['Age'], dtype='object')

In [46]:
null_value_table[null_value_table<30].index

Index(['Name', 'City', 'Purchaseamount', 'Feedback'], dtype='object')

In [48]:
df.drop(["Age"],axis=1)

      Name          City  Purchaseamount  Feedback
0    Alice      New York           100.0       5.0
1      Bob   Los Angeles             NaN       NaN
2  Charlie       Chicago           150.0       4.0
3    David       Houston           300.0       3.5
4      Eve       Phoenix           250.0       4.8
5    Frank  Philadelphia             NaN       NaN
6    Grace           NaN           350.0       3.8
7    Heidi     San Diego           450.0       4.9

In [ ]:
df[["Age","Feedback"]].fillna(df[["Age","Feedback"]].median(),inplace=True)

    Age  Feedback
0  25.0       5.0
1   NaN       NaN
2  35.0       4.0
3  40.0       3.5
4   NaN       4.8
5  50.0       NaN
6   NaN       3.8
7  60.0       4.9

## Minmax Scaling Formula: x'=((x-xmin)/(xmax-xmin)).
## you will get the range from 0 to 1.
## we apply min max scaling for each column then you will get in the range 0 to 1.

In [ ]:
from sklearn.impute import MinMaxScaler